//
//  PWFallbackFormatter.h
//  PWFoundation
//
//  Created by Frank Illenberger on 09.11.10.
//
//

// Formatter that wrapps formatters generated by PWValueTypes to append/remove a description
// of the nil-fallback value that the value type delivers via its fallbackKeyPath
@protocol PWValueTypeContext;

@interface PWFallbackFormatter : NSFormatter

- (instancetype)initWithFormatter:(NSFormatter*)formatter
                context:(id <PWValueTypeContext>)context
                options:(NSDictionary*)options
        fallbackKeyPath:(NSString*)fallbackKeyPath;

@property (nonatomic, readonly,  strong)    NSFormatter*               formatter;
@property (nonatomic, readonly,  strong)    id <PWValueTypeContext>    context;
@property (nonatomic, readonly,  copy)      NSDictionary*              options;
@property (nonatomic, readonly,  copy)      NSString*                  fallbackKeyPath;

// Receives the object on which the fallbackKeyPath is evaluated. Must be weak to prevent retain cycles as
// the formatters are cached but the object is prepared every time the cached formatter is used.
// As there is no good hook when formatting is finished, we cannot nil it after use ourselves.
@property (nonatomic, readwrite, weak)      id                         object;
@end
